### ISSUE TITLE
Missing Referral Details for Referred Users

### ISSUE THREAD

**Issue by hexonMD** [saasquatch/time-credit-theme#12]
Issue effects all three widget types:

When a user is referred the widget shows the active credit/discount in the basic referral stats but does not show and detail information. i.e. Who referred them. 

This referring user should be denoted in the details page as "Referred By" with everything else matching referred users.

**Comment by karlhorky** [comment]
@hexonMD We'll need a design for this.

**Comment by karlhorky** [comment]
Should the referrer user be displayed at the top of the list?

Also - not 100% sure that this makes sense to display in this list. This list is "Referrals", which are users referred by the user - not who referred the user.

I would expect this feature more as an annotation near a mini-profile of the user (top left maybe?). For instance:

![0e69a9f0-b2d7-11e4-817b-bd8658681379](https://cloud.githubusercontent.com/assets/1935696/6203537/fc36e4a8-b526-11e4-9574-af706875da52.jpg)

**Comment by karlhorky** [comment]
Hm, but I guess the drawback here is that you don't see the reward from your referrer clearly. You could make it a tooltip, but it would still not be very easy to find for most people.

**Comment by karlhorky** [comment]
Another alternative is that we change the text on the `Show Referrals` button to something like `Show Rewards`. Then at least it is accurate when we add the *Referrer* in this list as well.

**Comment by hexonMD** [comment]
I'd prefer to keep it in the list with the other referrals. Lets have the referral state tag be "Referred You". I'd also like to leave the button "show referrals" as is.

**Comment by karlhorky** [comment]
Okay, as discussed we'll keep it in the list with the other referrals and change the button text to "Show Details"
