### ISSUE TITLE
Vertical scroll bar in widget preview (SaaSquatch portal)

### ISSUE THREAD

**Issue by SupportSquatch** [saasquatch/time-credit-theme#17]
The widget preview has a vertical scroll bar. The button 'no referrals yet...' should move up to resolve this. 

This issue is (probably) not tied to just one theme, but applies to all themes. 

Please see the attached screenshot. 
![widget-vertical-scroll-bar](https://cloud.githubusercontent.com/assets/10427095/6238993/534a9134-b6b4-11e4-93f3-777534dda215.jpg)

**Comment by karlhorky** [comment]
What I will do is remove the referrals table when the list of users is empty, which should be done in any case.

Will this preview always have an empty referrals list? If so, this will fix the problem.

**Comment by hexonMD** [comment]
We have plans to one day have the ability to view the widget in different
referral states in the portal with dummy data. However, it would be coming
through as data so i assume your solution would still work.

-Mike
