### ISSUE TITLE
Adapt design to `mode` parameter

### ISSUE THREAD

**Issue by karlhorky** [saasquatch/time-credit-theme#2]
For instance, the design can appear differently in popup mode in comparison to embed mode.

For a first version of the embed mode, we can:
- [x] remove the following on `.squatch-container`:
  - [x] box shadow
  - [x] background color
  - [x] height
- [x] hide the close button
- [x] hide `.squatch-actions`
- [x] hide the `Hide Referrals` button

Possible values for `mode` are:

```
NOCONTENT
EMBED
HOSTED
POPUP
DEMO_EMBED
DEMO
```

**Comment by loganvolkers** [comment]
Just wanted to paste in this info from slack: https://saasquatch.slack.com/archives/themes/p1423082785000065

In the past we just added `mode` purely based on CSS.

In the HTML
```
<body class="mode-{{strlower mode}}>
<div class="container">
    ... content ...
</div>
</body>
```

In the CSS
```
.mode-popup .container{
   width: 400px; // popup fixed width
   border: 1px solid #000;
   background: #FFF;
}
.mode-embed .container{
   width: auto; // embed fluid width
   border: none;
   background: transparent;
}
.mode-popup .close{
   display:block; // show close button
}
.mode-embed .close{ 
  display:none;// hide the "close button" 
}
```

**Comment by karlhorky** [comment]
Yep, this looks like a good way to go.

**Comment by hexonMD** [comment]
Seems to be a bug with this. getting the following error on staging. Logan/Eric could you take a look?

Execution exception[[UncheckedExecutionException: com.github.jknack.handlebars.HandlebarsException: /templates/widget.hbs:48:55: could not find helper: 'strlower'
    <main class="squatch-container squatch-container-{{strlower mode}}">
                                                       ^
]]

**Comment by karlhorky** [comment]
Fixed in: 
https://github.com/saasquatch/time-credit-theme/commit/4f3f54f9e32d5bc6aff14fe974e725e94b76d2ae
https://github.com/saasquatch/percent-credit-theme/commit/9facb541fe133b667bdc967901fcd9d4396953eb
https://github.com/saasquatch/dollar-credit-theme/commit/d8de59cfbc07325b881955a4f1e213d101baebed
