### ISSUE TITLE
Long company names break widget

### ISSUE THREAD

**Issue by hexonMD** [saasquatch/time-credit-theme#6]
This issue effects all 3 widgets: Company name character limit of 16 lowercase characters. Anymore than that and the widget breaks. (or 7 capital W’s). A possible solution is to change the paragraph text size based on the word or character count using the following jquery 
http://css-tricks.com/set-font-size-based-on-word-count/
http://stackoverflow.com/questions/4466464/change-jquery-plugin-from-word-counting-to-character-plugin

**Comment by hexonMD** [comment]
![screen shot 2015-02-12 at 3 04 19 pm](https://cloud.githubusercontent.com/assets/3913256/6180158/0985bc90-b2d6-11e4-8194-d4f1ffe62cc2.png)

**Comment by karlhorky** [comment]
As discussed, we'll reduce the font size of the paragraph to `13px`, which will support long names. We'll keep an eye on this and if any longer names come up, we'll think this through again.
