### ISSUE TITLE
Referral Details list alignment off

### ISSUE THREAD

**Issue by hexonMD** [saasquatch/time-credit-theme#7]
Issue effects all 3 widget types: alignment of referral details is off: Referral Status should be more to the right and Username slightly more to the left.

**Comment by hexonMD** [comment]
Attached current state and mockup
![screen shot 2015-02-12 at 3 28 55 pm](https://cloud.githubusercontent.com/assets/3913256/6180249/0e694758-b2d7-11e4-98c5-a7030c7855d2.png)
![screen shot 2015-02-12 at 4 48 21 pm](https://cloud.githubusercontent.com/assets/3913256/6180250/0e69a9f0-b2d7-11e4-817b-bd8658681379.png)

**Comment by karlhorky** [comment]
As discussed, we'll reduce the font size of the paragraph to `13px`, which will support long names. We'll keep an eye on this and if any longer names come up, we'll think this through again.
